# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
permalink: /blog/:year/:month/:day/:title/
relative_permalinks: false
encoding: utf-8

# Setup
title:               DANIEL
#tagline:             'foo's website
description:         'Daniel web'
url: https://blog.escobar.eu.org
baseurl: "https://blog.escobar.eu.org"
urlimg: https://blog.escobar.eu.org/images/
#urlimg: https://daeshu.github.io/blog/images/
markdown: kramdown
kramdown:
  math_engine: mathjax

paginate: 5
paginate_path: "/blog/page:num"
excerpt_separator: <!--more-->
default_bg: sitebg.jpg
default_logo: sitelogo.png
safe: false
#timezone:    America/Chicago
future:      true


## code highlight options
syntax_highlighter: rouge
input: GFM

gems:
  - github-pages
  - font-awesome-sass
  - jekyll-redirect-from
  - jekyll-mentions

jekyll-mentions:
  base_url: https://twitter.com

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "rakefile", "README.md", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "LICENSE", "vendor", "assets", "_plugins", "public/dormant"]

# About/contact
author:
  name:              Daniel
  url:               https://twitter.com/DanielEscobarW
  avatar:           foo.png
  #email:           

# Owner/author information
owner:
  name:           Daniel
  avatar:         foo.png
  #email:          
  # Use the coder's toolbox at https://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:
  # Social networking links used in footer. Update and remove as you like.
  twitter:        DanielEscobarW
  facebook:       
  github:         
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:
  tumblr:  
  google_plus:    
  # orcid and google scholar IDs are different than standard username.
  orcid: 
  gscholar:

## sidebar links:
# For external links add external: true
links:
default_logo: '<a title="Daniel" href="/"><img src="https://sites.google.com/site/daesweb/_/rsrc/1498428880214/tesis/escobarzoho6.png" />'
  - title: <i class="iconside iconm-home"></i> Inicio
    url: /
  - title: <i class="iconside iconm-user"></i> Acerca de
    url: /about/
  - title: <i class="iconside iconm-quill"></i> Blog
    url: /blog/
  - title: <i class="fa fa-tags"></i> Etiquetas
    url: /tags/
  - title: <i class="fa fa-archive"></i> Archivo
    url: /archive/
  - title: <i class="iconside iconm-wordpress"></i> Mal Signo
    url: https://malsigno.wordpress.com
    external: true
  - title: <i class="iconside iconm-envelop"></i> Contacto
    url: /contact/
  - title: <i class="iconside iconm-twitter"></i> Twitter
    url: https://twitter.com/DanielEscobarW
    external: true
  - title: <i class="iconside iconm-feed2"></i> Feed
    url: /feed.xml

# Google Custom Search:
#google_search: xyz123abc

# Twitter stream widget:
# Replace xyz123abc with your twitter widget id from https://twitter.com/settings/widgets
twitter_widget_id: 471680276980957184

# Add disqus username for Disqus comment board:
#disqus_shortname: foo

# Analytics and webmaster tools stuff goes here
#google_analytics:   xyz123abc

## END ##
